language: python
dist: focal
python:
  - "3.11"
install:
  - pip install -r requirements_travis.txt
script:
  - python -m unittest discover

matrix:
  include:
    - python: "3.11"
      script: "flake8"
